name: overthelake
on:
  workflow_dispatch:
    inputs:
      userId:
        required: true
      transferId:
        required: true
      source:
        required: true
      destination:
        required: true
      size:
        required: true
jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - id: configure
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: echo "$RCLONE_CONF" > rclone.conf
      - id: rclone
        uses: docker://rclone/rclone:latest
        with:
          args: --config=rclone.conf --max-transfer=${{ github.event.inputs.size }}b --cutoff-mode=cautious copy "${{ github.event.inputs.source }}" "${{ github.event.inputs.destination }}"
        continue-on-error: true
      - id: webhook
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: >
          curl -H "Content-Type: application/json" -H "Authorization: Bearer $WEBHOOK_SECRET" -d '{"userId": "${{ github.event.inputs.userId }}", "transferId": "${{ github.event.inputs.transferId }}", "outcome": "${{ steps.rclone.outcome }}", "runId": ${{ github.run_id }}}' https://app.overlake.io/api/webhook/gitHub
